
import React, { createContext, useState, useContext, useEffect, ReactNode, PropsWithChildren } from 'react';

type Language = 'en' | 'am';

type Translations = {
  [key: string]: {
    en: string;
    am: string;
  }
};

export const dictionary: Translations = {
  // --- GENERAL ---
  dashboard: { en: "Dashboard", am: "ዋና ገጽ" },
  income: { en: "Income", am: "ገቢ" },
  expenditure: { en: "Expenditure", am: "ወጪ" },
  store: { en: "Store & Inventory", am: "ግምጃ ቤት" },
  audit: { en: "Audit Center", am: "ኦዲት ማዕከል" },
  notebook: { en: "Notebook", am: "ማስታወሻ" },
  search: { en: "Search & AI", am: "ፍለጋ እና AI" },
  editor: { en: "Data Editor", am: "ዳታ ማስተካከያ" },
  about: { en: "About Creator", am: "ስለ አዘጋጁ" },
  logout: { en: "Logout", am: "ውጣ" },
  login: { en: "Login", am: "ግባ" },
  username: { en: "Username", am: "መለያ ስም" },
  password: { en: "Password", am: "የይለፍ ቃል" },
  authenticate: { en: "AUTHENTICATE", am: "አረጋግጥና ግባ" },
  accessDenied: { en: "Invalid Credentials. Access Denied.", am: "የተሳሳተ መረጃ። መግባት አይችሉም።" },
  systemName: { en: "Auditing & Ration Management System", am: "የኦዲት እና ሬሽን አስተዳደር ሲስተም" },
  restrictedAccess: { en: "RESTRICTED ACCESS • ETHIOPIAN AIR FORCE", am: "የተገደበ መዳረሻ • የኢትዮጵያ አየር ኃይል" },
  initializing: { en: "Initializing Command Center...", am: "ሲስተሙን በማስጀመር ላይ..." },

  // --- PASSWORD RECOVERY & SYSTEM SETTINGS ---
  successAlert: { en: "Success Alert", am: "የስኬት ማሳሰቢያ" },
  accountRecoveryTerminal: { en: "Account Recovery Terminal", am: "የመለያ መልሶ ማግኛ ተርሚናል" },
  verifyIdentityChallenge: { en: "Verify your identity by answering the security challenge configured on this machine.", am: "በዚህ ኮምፒውተር ላይ የተቀመጠውን የደህንነት ጥያቄ በመመለስ ማንነትዎን ያረጋግጡ።" },
  securityQuestion: { en: "Security Question", am: "የደህንነት ጥያቄ" },
  yourAnswer: { en: "Your Answer", am: "የእርስዎ መልስ" },
  enterSecurityResponse: { en: "Enter security response...", am: "የደህንነት መልስዎን እዚህ ያስገቡ..." },
  verifyResponse: { en: "Verify Response", am: "መልስን አረጋግጥ" },
  identityConfirmed: { en: "Identity Confirmed", am: "ማንነት ተረጋግጧል" },
  setNewCredential: { en: "Set a new administrative security credential for your command terminal.", am: "ለተርሚናልዎ አዲስ የአስተዳዳሪ የደህንነት ይለፍ ቃል ያስቀምጡ።" },
  newPasswordLabel: { en: "New Password", am: "አዲስ የይለፍ ቃል" },
  confirmNewPasswordLabel: { en: "Confirm New Password", am: "አዲሱን የይለፍ ቃል ያረጋግጡ" },
  saveNewPassword: { en: "Save New Password", am: "አዲሱን የይለፍ ቃል አስቀምጥ" },
  forgotPassword: { en: "Forgot Password?", am: "የይለፍ ቃል ረሱ?" },
  systemAccessAndAiConfig: { en: "System Access & AI Configuration", am: "የሲስተም መግቢያ እና የAI ቅንጅቶች" },
  changeAdminCredentials: { en: "Change Administrative Credentials", am: "የአስተዳዳሪ መግቢያ መረጃን ይቀይሩ" },
  updateAccessParams: { en: "Update system access parameters for terminal logins.", am: "ለትእዛዝ ተርሚናል መግቢያ የደህንነት መለኪያዎችን ያሻሽሉ።" },
  leaveEmptyKeepCurrent: { en: "Leave empty to keep current", am: "አሁን ያለውን ለማቆየት ባዶ ይተውት" },
  securityRecoveryQuestion: { en: "Security Recovery Question", am: "ደህንነትን መልሶ ማግኛ ጥያቄ" },
  recoveryQuestionPlaceholder: { en: "e.g. Name of your first pet?", am: "ለምሳሌ የፊተኛው የቤት እንስሳዎ ስም?" },
  recoveryAnswer: { en: "Recovery Answer", am: "መልሶ ማግኛ መልስ" },
  updateRecoveryAnswerPlaceholder: { en: "Update recovery answer response", am: "የመልሶ ማግኛ ምላሽን ያሻሽሉ" },
  updateAccessCredentials: { en: "Update Access Credentials", am: "የመግቢያ መረጃን ያሻሽሉ" },
  geminiAiEngineApiKey: { en: "Gemini AI Engine API Key", am: "የGemini AI ሞተር API ቁልፍ" },
  geminiApiKeyDesc: { en: "Add your custom Gemini API key to power intelligent auditing and the chat assistant.", am: "የላቀ ኦዲት እና የውይይት ረዳቱን ለማንቀሳቀስ የእርስዎን Gemini API ቁልፍ እዚህ ያስገቡ።" },
  geminiApiKeyLabel: { en: "Gemini API Key", am: "የGemini API ቁልፍ" },
  geminiApiKeyPlaceholder: { en: "AI Studio API Key (reverts to default if empty)", am: "የAI Studio API ቁልፍ (ባዶ ከሆነ ወደ ቀድሞው ይመለሳል)" },
  saveApiKey: { en: "Save API Key", am: "የAPI ቁልፍ አስቀምጥ" },
  testCore: { en: "Test Core", am: "የሙከራ ጥያቄ" },
  sendTestMessageTooltip: { en: "Send test message to check key validity", am: "የቁልፉን ትክክለኛነት ለማረጋገጥ የሙከራ መልዕክት ይላኩ" },

  // --- SECTION HEADERS ---
  financials: { en: "Financials", am: "ፋይናንስ" },
  logistics: { en: "Logistics", am: "ሎጅስቲክስ" },
  system: { en: "System", am: "ሲስተም" },

  // --- ACTIONS ---
  save: { en: "Save", am: "አስቀምጥ" },
  saveChanges: { en: "Save Changes", am: "ለውጦችን አስቀምጥ" },
  cancel: { en: "Cancel", am: "ሰርዝ" },
  edit: { en: "Edit", am: "አስተካክል" },
  delete: { en: "Delete", am: "አጥፋ" },
  print: { en: "Print", am: "ፕሪንት" },
  export: { en: "Export", am: "ኤክስፖርት" },
  import: { en: "Import", am: "ኢምፖርት" },
  backup: { en: "Backup", am: "ባካፕ" },
  restore: { en: "Restore", am: "መልስ" },
  confirm: { en: "Confirm", am: "አረጋግጥ" },
  add: { en: "Add", am: "ጨምር" },
  analyze: { en: "Analyze", am: "ተንትን" },
  close: { en: "Close", am: "ዝጋ" },
  download: { en: "Download", am: "አውርድ" },
  upload: { en: "Upload", am: "ጫን" },
  reset: { en: "Reset", am: "ባዶ አድርግ" },
  apply: { en: "Apply", am: "ተግብር" },
  dismiss: { en: "Dismiss", am: "አጥፋ" },
  view: { en: "View", am: "ተመልከት" },

  // --- DATA TOOLS & POPUPS ---
  noDataExport: { en: "No data to export", am: "የሚላክ መረጃ የለም" },
  secBlockPart1: { en: "SECURITY BLOCK: File name mismatch! You cannot import", am: "የደህንነት እገዳ፡ የፋይል ስም አይዛመድም!" },
  secBlockPart2: { en: "into the", am: "ወደ" },
  secBlockPart3: { en: "section.", am: "ክፍል ማስገባት አይችሉም።" },
  importFailed: { en: "Failed: File is empty or invalid format.", am: "ስህተት፡ ፋይሉ ባዶ ነው ወይም አጻጻፉ ትክክል አይደለም።" },
  importSuccessPart1: { en: "Success: Imported", am: "ተሳክቷል፡" },
  importSuccessPart2: { en: "new records into", am: "አዳዲስ መዝገቦች ወደ" },
  importSuccessPart3: { en: "!", am: " ገብተዋል!" },
  actionBlocked: { en: "Action Blocked", am: "ተግባሩ ታግዷል" },
  successTitle: { en: "Success", am: "ተሳክቷል" },

  // --- DUPLICATE DETECTION ---
  duplicateDetected: { en: "Duplicate Data Detected", am: "ተመሳሳይ መረጃ ተገኝቷል" },
  duplicateMsg: { en: "The system found an existing entry that matches what you are trying to save.", am: "ለማስገባት የሞከሩት መረጃ በዳታቤዝ ውስጥ አለ።" },
  merge: { en: "Merge (Add Together)", am: "ደምር" },
  createNew: { en: "Create New Entry", am: "ለብቻው መዝግብ" },
  proceedAnyway: { en: "Proceed Anyway", am: "ዝም ብለህ መዝግብ" },
  matchingField: { en: "Matching Field", am: "የተመሳሰለው" },
  
  // --- GITHUB SYNC ---
  githubSync: { en: "GitHub Cloud Sync", am: "GitHub ክላውድ" },
  githubDesc: { en: "Connect to GitHub to automatically backup your database.", am: "ዳታቤዝዎን በራስ-ሰር ባካፕ ለማድረግ ከ GitHub ጋር ያገናኙ።" },
  repoOwner: { en: "Repository Owner (Username)", am: "የሪፖ ባለቤት (መለያ ስም)" },
  repoName: { en: "Repository Name", am: "የሪፖ ስም" },
  filePath: { en: "File Path (e.g., db.json)", am: "የፋይል ስም (ለምሳሌ db.json)" },
  patToken: { en: "Personal Access Token", am: "ሚስጥራዊ ቁልፍ (PAT)" },
  syncEnabled: { en: "Enable Auto-Sync", am: "አውቶማቲክ ባካፕን አብራ" },
  syncNow: { en: "Sync Now", am: "አሁን አገናኝ" },
  githubConnected: { en: "Connected to GitHub", am: "ከ GitHub ጋር ተገናኝቷል" },
  githubError: { en: "Connection Failed", am: "መገናኘት አልተቻለም" },
  pullingData: { en: "Pulling data from GitHub...", am: "መረጃ ከ GitHub በመቀበል ላይ..." },
  pushingData: { en: "Pushing data to GitHub...", am: "መረጃ ወደ GitHub በመላክ ላይ..." },

  // --- HOME PAGE ---
  netPosition: { en: "Net Financial Position", am: "የፋይናንስ ቁመና" },
  totalInflow: { en: "Total Inflow", am: "ጠቅላላ ገቢ" },
  totalOutflow: { en: "Total Outflow", am: "ጠቅላላ ወጪ" },
  dailyAvg: { en: "Daily Averages", am: "ዕለታዊ አማካይ" },
  day: { en: "Day", am: "ቀን" },
  runway: { en: "Cash Runway", am: "የካሽ ዕድሜ" },
  surplusDuration: { en: "Surplus Duration", am: "የካሽ ቆይታ ጊዜ" },
  daysUntilCash0: { en: "Days until cash reaches 0", am: "ገንዘብ እስኪያልቅ የቀሩ ቀናት" },
  days: { en: "Days", am: "ቀናት" },
  manpower: { en: "Manpower", am: "የሰው ኃይል" },
  clickForRoster: { en: "Click for Roster", am: "ዝርዝር ይመልከቱ" },
  salesIncome: { en: "Sales Income", am: "የሽያጭ ገቢ" },
  clickForSales: { en: "Click for Sales Log", am: "የሽያጭ ዝርዝር" },
  storeValue: { en: "Store Value", am: "የግምጃ ቤት ዋጋ" },
  clickForInv: { en: "Click for Inventory", am: "ዕቃ ዝርዝር" },
  refunds: { en: "Refunds", am: "ተመላሽ" },
  clickForLog: { en: "Click for Log", am: "ተመላሽ ዝርዝር" },
  marketVolatility: { en: "Market Price Volatility", am: "የገበያ ዋጋ ንረት" },
  volatilityDescription: { en: "Real-time tracking of item price fluctuations based on purchase history.", am: "በግዢ ታሪክ ላይ የተመሰረተ የዕቃዎች ዋጋ መዋዠቅ ክትትል።" },
  avgPriceHike: { en: "Avg Price Hike", am: "አማካይ ጭማሪ" },
  avgPriceDrop: { en: "Avg Price Drop", am: "አማካይ ቅናሽ" },
  inflation: { en: "Inflation (Price Increase)", am: "የዋጋ ንረት (ጭማሪ)" },
  deflation: { en: "Deflation (Price Decrease)", am: "የዋጋ ቅናሽ" },
  searchTrends: { en: "Search Trends", am: "ዝርዝር ትንታኔ" },
  avgFluctuation: { en: "Average Market Price Fluctuation", am: "አማካይ የገበያ ዋጋ መዋዠቅ" },
  monthly: { en: "Monthly", am: "ወርሃዊ" },
  daily: { en: "Daily", am: "ዕለታዊ" },
  month: { en: "Month", am: "ወር" },
  year: { en: "Year", am: "ዓመተ ምህረት" },
  dateLabel: { en: "Date", am: "ቀን" },
  noTrendData: { en: "No sufficient data to display trends.", am: "በቂ መረጃ የለም።" },
  topExpenses: { en: "Top Expenses", am: "ከፍተኛ ወጪዎች" },
  topIncome: { en: "Top Income Sources", am: "ከፍተኛ ገቢዎች" },
  expenditureBreakdown: { en: "Expenditure Breakdown", am: "የወጪ ዝርዝር ሁኔታ" },
  market: { en: "Market", am: "ገበያ" },
  wage: { en: "Wage", am: "ደመወዝ" },
  operationalExpense: { en: "Others Cost", am: "ልዩ ልዩ ወጪ" },
  recentActivity: { en: "Recent Activity Log", am: "የቅርብ ጊዜ እንቅስቃሴዎች" },
  type: { en: "Type", am: "ዓይነት" },
  description: { en: "Description", am: "ዝርዝር መግለጫ" },
  date: { en: "Date", am: "ቀን" },
  amount: { en: "Amount", am: "መጠን" },
  birr: { en: "Birr", am: "ብር" },
  ethiopianDate: { en: "Ethiopian Date", am: "የኢትዮጵያ ቀን" },
  systemStatus: { en: "System Status", am: "የሲስተም ሁኔታ" },
  dbIntegrity: { en: "Database Integrity Check", am: "የዳታቤዝ ጤንነት" },
  online: { en: "ONLINE", am: "ኦንላይን" },
  rank: { en: "Rank", am: "ማዕረግ" },
  firstName: { en: "First Name", am: "ስም" },
  lastName: { en: "Last Name", am: "የአባት ስም" },
  quantity: { en: "Quantity", am: "ብዛት" },
  totalCost: { en: "Total Cost", am: "ጠቅላላ ዋጋ" },
  item: { en: "Item", am: "ዕቃ" },
  itemName: { en: "Item Name", am: "የዕቃው ስም" },
  inStock: { en: "In Stock", am: "ያለ" },
  estimatedValue: { en: "Est. Value", am: "ግምታዊ ዋጋ" },
  manpowerEntry: { en: "Manpower Entry", am: "የሰው ኃይል መዝገብ" },
  noOptions: { en: "No options available", am: "ምንም አማራጭ የለም" },

  // --- INCOME PAGE ---
  incomeManagement: { en: "Income Management", am: "የገቢ አስተዳደር" },
  incomeSubtitle: { en: "Track payroll, sales, subsidies, and transfers.", am: "ፔይሮል፣ ሽያጭ፣ ድጎማ እና በጀት ያስተዳድሩ።" },
  duplicateCheck: { en: "Duplicate Check Active: Existing entries with same name will be merged.", am: "ተመሳሳይ ስም ያለው መረጃ ካለ ይደመራል።" },
  smartMerge: { en: "Smart Merge: Same items sold on different dates will be tracked separately, but stock averaged.", am: "ተመሳሳይ ዕቃዎች ሲጨመሩ የዋጋ አማካይ ይሰላል።" },
  command: { en: "Command", am: "ኮማንድ" },
  selectRank: { en: "Select Rank", am: "ማዕረግ ይምረጡ" },
  amountBirr: { en: "Amount (Birr)", am: "መጠን (ብር)" },
  startDate: { en: "Start Date", am: "የጀመረበት ቀን" },
  endDate: { en: "End Date", am: "የሚያበቃበት ቀን" },
  itemSold: { en: "Items Sold", am: "የተሸጡ ዕቃዎች" },
  itemSalesEntry: { en: "Item Sales Entry", am: "የዕቃ ሽያጭ መዝገብ" },
  unit: { en: "Unit", am: "መለኪያ" },
  selectUnit: { en: "Select Unit", am: "መለኪያ ይምረጡ" },
  singlePrice: { en: "Single Price", am: "የአንዱ ዋጋ" },
  dateSold: { en: "Date Sold", am: "የተሸጠበት ቀን" },
  subsidyRecord: { en: "Subsidy Record", am: "የድጎማ መዝገብ" },
  subsidyType: { en: "Subsidy Type", am: "የድጎማ ዓይነት" },
  subsidyFinancial: { en: "Financial", am: "የገንዘብ ድጋፍ" },
  subsidyFood: { en: "Food", am: "የምግብ ድጎማ" },
  source: { en: "Source", am: "ምንጭ" },
  dateReceived: { en: "Date Received", am: "የተቀበለበት ቀን" },
  budgetTransfer: { en: "Budget Transfer", am: "የበጀት ዝውውር" },
  amountTransferred: { en: "Amount Transferred", am: "የተላለፈው ገንዘብ" },
  monthFrom: { en: "Transfer From (Month)", am: "ከየትኛው ወር" },
  monthTo: { en: "Transfer To (Month)", am: "ወደ የትኛው ወር" },
  selectMonth: { en: "Select Month", am: "ወር ይምረጡ" },
  confirmSave: { en: "Confirm & Save Transaction", am: "አረጋግጥ እና አስቀምጥ" },

  // --- EXPENDITURE PAGE ---
  expenditureManagement: { en: "Expenditure Management", am: "የወጪ አስተዳደር" },
  expenditureSubtitle: { en: "Track market purchases, wages, and operational costs.", am: "የገበያ ግዢ፣ የሰራተኛ ደመወዝ እና ልዩ ልዩ ወጪዎች።" },
  marketPurchase: { en: "Market Purchase", am: "የገበያ ግዢ" },
  marketMergeMsg: { en: "Same items bought multiple times will be averaged in reports.", am: "ተመሳሳይ ዕቃዎች ሲገዙ ዋጋቸው በአማካይ ይሰላል።" },
  wagePayment: { en: "Wage Payment", am: "የደመወዝ ክፍያ" },
  workerName: { en: "Worker Name", am: "የሰራተኛው ስም" },
  positionJob: { en: "Position / Job", am: "የሥራ መደብ" },
  paymentAmount: { en: "Payment Amount", am: "የክፍያ መጠን" },
  reasonTitle: { en: "Reason / Expense Title", am: "የወጪው ምክንያት / ርዕስ" },
  refundIssuance: { en: "Refund Issuance", am: "ተመላሽ ገንዘብ" },
  refundAmount: { en: "Refund Amount", am: "የተመላሽ መጠን" },
  refundDate: { en: "Stop Date (Refund Date)", am: "የቆመበት ቀን (ተመላሽ ቀን)" },
  confirmExpense: { en: "Confirm Expense", am: "ወጪውን አረጋግጥ" },

  // --- STORE PAGE & GENERAL UNITS ---
  storeData: { en: "Store Data", am: "የግምጃ ቤት መረጃ" },
  itemList: { en: "Item List", am: "የዕቃዎች ዝርዝር" },
  orders: { en: "Orders", am: "ትዕዛዞች" },
  transfers: { en: "Transfers", am: "ዝውውር" },
  foodProgram: { en: "Food Program", am: "የምግብ ፕሮግራም" },
  logisticsAi: { en: "Logistics AI", am: "ሎጅስቲክስ AI" },
  newItem: { en: "New Store Item", am: "አዲስ ዕቃ ወደ ግምጃ ቤት" },
  price: { en: "Price", am: "ዋጋ" },
  recentLogs: { en: "Recent Logs", am: "የቅርብ ጊዜ ምዝገባዎች" },
  last3Days: { en: "(Last 3 Active Days)", am: "(ባለፉት 3 ቀናት)" },
  records: { en: "Records", am: "መዝገቦች" },
  fullHistory: { en: "Full History", am: "ሙሉ ታሪክ" },
  createOrder: { en: "Create Order", am: "ትዕዛዝ መፍጠሪያ" },
  buyer: { en: "Buyer Name", am: "ገዢው ስም" },
  addToCart: { en: "Add to Cart", am: "ወደ ዘንቢል ጨምር" },
  currentCart: { en: "Current Cart", am: "የዘንቢል ይዘት" },
  pendingOrders: { en: "Pending Orders", am: "በሂደት ላይ ያሉ ትዕዛዞች" },
  pending: { en: "Pending", am: "በሂደት ላይ" },
  receive: { en: "Receive", am: "ረከብ" },
  done: { en: "Done", am: "ተጠናቀቀ" },
  newMonthlyTransfer: { en: "New Monthly Transfer", am: "አዲስ የወር ዝውውር" },
  fromMonth: { en: "From Month", am: "ከወር" },
  toMonth: { en: "To Month", am: "ወደ ወር" },
  recentTransfers: { en: "Recent Transfers", am: "የቅርብ ጊዜ ዝውውሮች" },
  weeklyFoodSchedule: { en: "Weekly Food Schedule", am: "ሳምንታዊ የምግብ ፕሮግራም" },
  saveConfig: { en: "Save & Archive", am: "አስቀምጥ እና አርካይቭ አድርግ" },
  saveProgramConfirm: { en: "Do you want to overwrite the current weekly schedule? You can also archive this version for history.", am: "ያለውን ሳምንታዊ ፕሮግራም መቀየር ይፈልጋሉ? ይህን ፕሮግራም እንደ ታሪክ ማስቀመጥም ይችላሉ።" },
  archiveThisVersion: { en: "Archive this version", am: "ይህን ስሪት አርካይቭ አድርግ" },
  archiveNamePlaceholder: { en: "Archive Name (Optional)", am: "የአርካይቭ ስም (አማራጭ)" },
  logisticsTitle: { en: "Logistics Intelligence", am: "የሎጅስቲክስ ትንታኔ" },
  logisticsSubtitle: { en: "AI-Powered Analysis of Stock vs Consumption", am: "በ AI የታገዘ ስቶክ እና ፍጆታ ትንታኔ" },
  currentManpower: { en: "Current Manpower", am: "አሁን ያለ የሰው ኃይል" },
  analyzeStock: { en: "Analyze Stock", am: "ስቶክን ተንትን" },
  autoGenMenu: { en: "Auto-Generate Menu", am: "ሜኑ በራስ-ሰር አዘጋጅ" },
  criticalAlerts: { en: "Critical Alerts", am: "አሳሳቢ ማስጠንቀቂያዎች" },
  purchasingRecs: { en: "Purchasing Recommendations", am: "የግዢ ምክሮች" },
  stockDuration: { en: "Stock Duration Analysis", am: "የስቶክ ቆይታ ትንታኔ" },
  optimizedMenu: { en: "Optimized Menu Preview", am: "የተሻሻለ ሜኑ እይታ" },
  applyMenu: { en: "Apply Menu", am: "ሜኑን ተጠቀም" },
  neuralProcessing: { en: "Neural Processing...", am: "በማስላት ላይ..." },
  awaitingAnalysis: { en: "Awaiting Analysis Request", am: "ትዕዛዝ በመጠበቅ ላይ" },
  storeSubtitle: { en: "Manage inventory, process orders, and schedule food programs.", am: "ስቶክ፣ ትዕዛዝ እና የምግብ ፕሮግራም ያስተዳድሩ።" },
  receiveStock: { en: "Receive Stock", am: "ዕቃ ረከብ" },
  itemOrdered: { en: "Item Ordered", am: "የታዘዘው ዕቃ" },
  reqAmount: { en: "Requested Amount", am: "የተጠየቀው መጠን" },
  actAmount: { en: "Actual Amount Received", am: "የተረከበው መጠን" },
  unitPrice: { en: "Price Per Unit (Birr)", am: "የአንዱ ዋጋ (ብር)" },
  dailyRecipe: { en: "Daily Recipe", am: "የዕለቱ የምግብ አዘገጃጀት" },
  baseManpowerRecipe: { en: "Base Manpower for this Recipe", am: "ለዚህ አዘገጃጀት የታሰበ የሰው ኃይል" },
  addItem: { en: "Add Item", am: "ዕቃ ጨምር" },
  issueRation: { en: "Issue Daily Ration", am: "የዕለቱን ሬሽን አውጣ" },
  currentHeadcount: { en: "Current Headcount (Manpower)", am: "የአሁን የሰው ኃይል ብዛት" },
  calcRecipeMsg: { en: "Calculated based on recipe scaling.", am: "በአዘገጃጀቱ መሰረት የተሰላ" },
  deductList: { en: "Items to Deduct from Inventory", am: "ከስቶክ የሚቀነስ ዕቃ" },
  confirmDeduct: { en: "Confirm & Deduct", am: "አረጋግጥና ቀንስ" },
  itemAddedMsg: { en: "Item added (Merged if duplicate).", am: "ዕቃው ተመዝግቧል (ተመሳሳይ ካለ ተደምሯል)።" },
  deleteItemConfirm: { en: "Are you sure you want to remove this item from the store inventory?", am: "ይህን ዕቃ ከግምጃ ቤት መሰረዝ ይፈልጋሉ?" },
  ordersSubmittedMsg: { en: "Orders Submitted Successfully!", am: "ትዕዛዞቹ ተልከዋል!" },
  transferSavedMsg: { en: "Transfer Record Saved (Merged if duplicate).", am: "ዝውውሩ ተመዝግቧል (ተመሳሳይ ካለ ተደምሯል)።" },
  programSavedMsg: { en: "Program Saved & Archived", am: "ፕሮግራሙ ተቀምጧል" },
  recipeSavedMsg: { en: "Daily Recipe Saved Successfully.", am: "የዕለቱ የምግብ አዘገጃጀት ተቀምጧል።" },
  analysisFailed: { en: "Analysis failed. Check connection.", am: "ትንታኔው አልተሳካም። ኮኔክሽን ያረጋግጡ።" },
  manpowerError: { en: "Error: Manpower count must be greater than 0", am: "ስህተት፡ የሰው ኃይል ቁጥር ከ 0 መብለጥ አለበት።" },
  aiMenuApplied: { en: "AI Menu Applied to Table. Please Review & Save.", am: "AI ሜኑ ገብቷል። እባክዎ ያረጋግጡና ያስቀምጡ።" },
  addedToCart: { en: "Added {item} to Order Cart", am: "{item} ወደ ትዕዛዝ ዘንቢል ገብቷል።" },
  noRecentItems: { en: "No items recorded in the last 3 active days.", am: "ባለፉት 3 ቀናት የተመዘገበ የለም።" },
  noPendingOrders: { en: "No pending orders found.", am: "ምንም ያልተጠናቀቀ ትዕዛዝ የለም።" },
  completed: { en: "Completed", am: "ተጠናቀቀ" },
  transferInfo: { en: "Transfer Info", am: "የዝውውር መረጃ" },
  requiredWk: { en: "Required (Wk)", am: "ፍላጎት (ሳምንት)" },
  estDaysLeft: { en: "Est. Days Left", am: "የቀረው ቀን" },
  printMode: { en: "Print Mode", am: "ፕሪንት" },
  recipe: { en: "Recipe", am: "አዘገጃጀት" },
  issue: { en: "Issue", am: "አውጣ" },
  generated: { en: "Generated", am: "የተዘጋጀው" },
  action: { en: "Action", am: "ተግባር" },
  breakfast: { en: "Breakfast", am: "ቁርስ" },
  lunch: { en: "Lunch", am: "ምሳ" },
  dinner: { en: "Dinner", am: "እራት" },

  // --- RANKS & COMMANDS ---
  "Air Force": { en: "Air Force", am: "አየር ኃይል" },
  "Ground Force": { en: "Ground Force", am: "ምድር ኃይል" },
  "Navy": { en: "Navy", am: "ባህር ኃይል" },
  "Special Force": { en: "Special Force", am: "ልዩ ኃይል" },
  "Others": { en: "Others", am: "ሌሎች" },
  "Enlisted": { en: "Enlisted", am: "የበታች ሹም" },
  "Recruit": { en: "Recruit", am: "ምልምል" },
  "Private": { en: "Private", am: "መሰረታዊ ወታደር" },
  "Lance CPL": { en: "Lance CPL", am: "ም/አስር አለቃ" },
  "Corporal": { en: "Corporal", am: "አስር አለቃ" },
  "Sergeant": { en: "Sergeant", am: "ሃምሳ አለቃ" },
  "NCOs": { en: "NCOs", am: "ባለ ሌላ ማዕረግተኛ" },
  "Officers": { en: "Officers", am: "መኮንኖች" },
  "Second Lieutenant": { en: "Second Lieutenant", am: "ም/መቶ አለቃ" },
  "Lieutenant": { en: "Lieutenant", am: "መቶ አለቃ" },
  "Captain": { en: "Captain", am: "ሻምበል" },
  "Major": { en: "Major", am: "ሻለቃ" },
  "Lieutenant Colonel": { en: "Lieutenant Colonel", am: "ሌተናል ኮሎኔል" },
  "Colonel": { en: "Colonel", am: "ኮሎኔል" },
  "Seaman Recruit": { en: "Seaman Recruit", am: "ምልምል መርከበኛ" },
  "Seaman": { en: "Seaman", am: "መርከበኛ" },
  "Leading Seaman": { en: "Leading Seaman", am: "መሪ መርከበኛ" },
  "Petty Officers": { en: "Petty Officers", am: "ፔቲ ኦፊሰሮች" },

  // --- MANPOWER TYPES ---
  "Payroll": { en: "Payroll", am: "ፔይሮል" },
  "Full Cash": { en: "Full Cash", am: "ሙሉ ከፋይ" },
  "Half Cash": { en: "Half Cash", am: "ተቆራራጭ ከፋይ" },
  "Transient": { en: "Transient", am: "ትራንዚንት" },
  "Pension": { en: "Pension", am: "ጡረታ" },

  // --- UNITS & DAYS ---
  Kg: { en: "Kg", am: "ኪ.ግ" },
  Gram: { en: "Gram", am: "ግራም" },
  Litre: { en: "Litre", am: "ሊትር" },
  Quintal: { en: "Quintal", am: "ኩንታል" },
  Meter: { en: "Meter", am: "ሜትር" },
  Count: { en: "Count", am: "ፍሬ" },
  Pack: { en: "Pack", am: "ፓኬት" },
  Carton: { en: "Carton", am: "ካርቶን" },
  Tasa: { en: "Tasa", am: "ጣሳ" },
  Jerkan: { en: "Jerkan", am: "ጄሪካን" },
  Esir: { en: "Esir", am: "እሥር" },
  Dozen: { en: "Dozen", am: "ደርዘን" },
  Medeb: { en: "Medeb", am: "መደብ" },
  Monday: { en: "Monday", am: "ሰኞ" },
  Tuesday: { en: "Tuesday", am: "ማክሰኞ" },
  Wednesday: { en: "Wednesday", am: "ረቡዕ" },
  Thursday: { en: "Thursday", am: "ሐሙስ" },
  Friday: { en: "Friday", am: "አርብ" },
  Saturday: { en: "Saturday", am: "ቅዳሜ" },
  Sunday: { en: "Sunday", am: "እሁድ" },

  // --- AUDIT PAGE ---
  auditCenter: { en: "Audit Center", am: "የኦዲት ማዕከል" },
  auditSubtitle: { en: "Generate automated reports, manual docs, and manage DB.", am: "የኦዲት ሪፖርቶችን ያዘጋጁ እና ዳታቤዝ ያስተዳድሩ።" },
  selectSection: { en: "Select Section", am: "ክፍል ይምረጡ" },
  automatedAudit: { en: "Automated Audit", am: "አውቶማቲክ ኦዲት" },
  manualAudit: { en: "Manual Audit", am: "ማኑዋል ኦዲት" },
  calculators: { en: "Calculators", am: "ካልኩሌተሮች" },
  dbAdmin: { en: "DB Admin", am: "ዳታቤዝ አስተዳደር" },
  reportConfig: { en: "Report Configuration", am: "የሪፖርት ማስተካከያ" },
  fiscalYear: { en: "Fiscal Year", am: "በጀት ዓመት" },
  recipientLabel: { en: "Recipient", am: "ለማን" },
  recipientPlaceholder: { en: "e.g. Commander", am: "ለምሳሌ፡ አዛዥ" },
  city: { en: "City", am: "ከተማ" },
  subjectPrefix: { en: "Subject Prefix", am: "ጉዳዩ" },
  subjectPlaceholder: { en: "Subject...", am: "ጉዳዩ..." },
  pageCount: { en: "Page Count", am: "የገጽ ብዛት" },
  pageCountPlaceholder: { en: "e.g. 3", am: "ለምሳሌ 3" },
  chairmanName: { en: "Chairman Name", am: "የሰብሳቢ ስም" },
  chairmanTitle: { en: "Chairman Title", am: "የሰብሳቢ ማዕረግ/ኃላፊነት" },
  chairmanTitlePlaceholder: { en: "Title...", am: "ኃላፊነት..." },
  auditorName: { en: "Auditor Name", am: "የኦዲተር ስም" },
  printReport: { en: "Print Report", am: "ሪፖርት ፕሪንት" },
  downloadPdf: { en: "Download PDF", am: "ፒዲኤፍ አውርድ" },
  downloadDocx: { en: "Download DOCX", am: "DOCX አውርድ" },
  printPreview: { en: "Print Preview", am: "ቅድመ እይታ" },
  closePreview: { en: "Close Preview", am: "ቅድመ እይታ ዝጋ" },
  printNow: { en: "Print Now", am: "ፕሪንት አድርግ" },
  clickPreview: { en: "Click to Preview / Print", am: "ለማየት / ፕሪንት ለማድረግ ይጫኑ" },
  generatedOn: { en: "Generated on", am: "የተዘጋጀው በ" },
  overpaidAmount: { en: "Overpaid Amount", am: "ተጨማሪ ክፍያ" },
  
  // --- AUDIT REPORT BODY STRINGS (MODIFIED FOR TARGETED REPLACEMENT) ---
  auditReportFor: { en: "Audit Report for", am: "የ" },
  auditSubjectSuffix: { en: "Logistics Audit", am: "ወር ሪፖርት ስለማቅረብ ይመለከታል" },
  auditBodyIntro: { en: "This audit report covers the month of", am: "በጉዳዩ ለመግለጽ እንደተሞከረው የ" },
  auditBodyMid: { en: "in the year", am: "ወር" },
  auditBodyEnd: { en: "listing all incomes and expenditures. Total pages:", am: "ዓ/ም የግብር ቤት ኦዲት" },
  auditBodyPages: { en: "pages.", am: "ገፅ አባሪ አድርገን የላክን መሆኑን በአክብሮት እንገልጻለን።" },
  
  withRegards: { en: "With Regards", am: "ከሰላምታ ጋር" },
  auditor: { en: "Auditor", am: "ኦዲተር" },
  incomeExpenseSummary: { en: "Income & Expense Summary", am: "የገቢ እና ወጪ ማጠቃለያ" },
  incomeTitle: { en: "INCOME", am: "ገቢ" },
  payrollCount: { en: "Payroll Count", am: "የፔይሮል ብዛት" },
  groundForce: { en: "Ground Force", am: "ምድር ኃይል" },
  fullCash: { en: "Full Cash", am: "ሙሉ ከፋይ" },
  halfCash: { en: "Half Cash", am: "ተቆራራጭ ከፋይ" },
  people: { en: "people", am: "ሰው" },
  transient: { en: "Transient", am: "ትራንዚንት" },
  miscIncome: { en: "Misc. Sales/Income", am: "የተለያየ ሽያጭ/ገቢ" },
  transferFromPrev: { en: "Transfer (Prev Month)", am: "የወር ዝውውር" },
  totalIncome: { en: "TOTAL INCOME", am: "ጠቅላላ ገቢ" },
  expenditureTitle: { en: "EXPENDITURE", am: "ወጪ" },
  refund: { en: "Refund", am: "ብር ተመላሽ" },
  otherCosts: { en: "Other Costs", am: "ሌሎች ወጪዎች" },
  totalExpense: { en: "TOTAL EXPENSE", am: "ጠቅላላ ወጪ" },
  netBalance: { en: "NET BALANCE", am: "ከወጪ ቀሪ" },
  marketListTitle: { en: "Market Expense Details", am: "የገበያ ወጪ ዝርዝር" },
  sno: { en: "S.No", am: "ተ.ቁ" },
  itemType: { en: "Item Type", am: "የዕቃ ዓይነት" },
  measurement: { en: "Unit", am: "መለኪያ" },
  totalPrice: { en: "Total Price", am: "ጠቅላላ ዋጋ" },
  noMarketData: { en: "No market data found for this month.", am: "ለዚህ ወር የገበያ መረጃ የለም።" },
  transferNextTitle: { en: "Items Transfer to Next Month", am: "ወደሚቀጥለው ወር በንብረት የዞረ" },
  estimation: { en: "Estimation", am: "ግምታዊ ዋጋ" },
  noTransferData: { en: "No transfers found.", am: "ምንም ዝውውር የለም።" },
  manpowerRosterTitle: { en: "Manpower Roster", am: "የሰው ኃይል ዝርዝር" },
  name: { en: "Name", am: "ስም" },
  payment: { en: "Payment", am: "ክፍያ" },
  noManpowerData: { en: "No manpower records found.", am: "የሰው ኃይል መረጃ የለም።" },
  
  // --- MANUAL AUDIT & CALC ---
  manualReport: { en: "Manual Audit Report", am: "ማኑዋል ኦዲት ሪፖርት" },
  saveDoc: { en: "Save as DOC", am: "DOC አስቀምጥ" },
  startTyping: { en: "Start typing your report here...", am: "ሪፖርትዎን እዚህ መጻፍ ይጀምሩ..." },
  marketCalc: { en: "Market Calculator", am: "የገበያ ካልኩሌተር" },
  openStdCalc: { en: "Open Std. Calculator", am: "ካልኩሌተር ክፈት" },
  resetForm: { en: "Reset Form", am: "ቅጽ አጽዳ" },
  itemQty: { en: "Item Qty", am: "ብዛት" },
  cost: { en: "Cost", am: "ዋጋ" },
  total: { en: "Total", am: "ጠቅላላ" },
  addNewRow: { en: "Add New Row", am: "አዲስ ተራ ቁጥር" },
  totalQty: { en: "Total Qty", am: "ጠቅላላ ብዛት" },
  avgSinglePrice: { en: "Avg Single Price", am: "አማካይ የአንዱ ዋጋ" },
  tacticalCalc: { en: "Tactical Calculator", am: "ታክቲካል ካልኩሌተር" },
  
  // --- DB ADMIN ---
  dbAdministration: { en: "Database Administration", am: "ዳታቤዝ አስተዳደር" },
  systemBackup: { en: "System Backup", am: "ሲስተም ባካፕ" },
  safeZone: { en: "Safe Zone", am: "አስተማማኝ" },
  backupDesc: { en: "Download a full copy of the entire system database (JSON). Keep this safe.", am: "የሲስተሙን ሙሉ ዳታ (JSON) ያውርዱ። ይህን ፋይል በጥንቃቄ ያስቀምጡ።" },
  downloadBackup: { en: "Download Full Backup", am: "ሙሉ ባካፕ አውርድ" },
  restoreData: { en: "Restore Data", am: "ዳታ መልስ" },
  overwriteMode: { en: "Overwrite Mode", am: "ሙሉ በሙሉ ይቀይራል" },
  restoreDesc: { en: "Upload a backup file to restore the system. WARNING: This replaces current data.", am: "ባካፕ ፋይል በመጫን ሲስተሙን ይመልሱ። ማስጠንቀቂያ፦ ያለዎትን መረጃ በሙሉ ይቀይረዋል።" },
  selectBackup: { en: "Select Backup File", am: "ባካፕ ፋይል ይምረጡ" },
  confirmRestore: { en: "Confirm System Restore", am: "ሲስተም መመለስን ያረጋግጡ" },
  restoreWarning1: { en: "Are you sure you want to restore from:", am: "እርግጠኛ ነዎት? ከዚህ ፋይል ነው የሚመለሰው፦" },
  restoreWarning2: { en: "WARNING: This will overwrite ALL current data.", am: "ማስጠንቀቂያ፦ ይህ ያለዎትን መረጃ በሙሉ ያጠፋል።" },
  readingBackup: { en: "Reading backup file...", am: "ፋይሉን በማንበብ ላይ..." },
  readFailed: { en: "Failed to read file.", am: "ፋይሉን ማንበብ አልተቻለም።" },
  saveError: { en: "Error saving to database.", am: "ወደ ዳታቤዝ ማስገባት አልተቻለም።" },
  restoreSuccess: { en: "System Restored Successfully! Reloading...", am: "ሲስተሙ በትክክል ተመልሷል! በመጫን ላይ..." },
  invalidBackup: { en: "Invalid Backup File Structure.", am: "የባካፕ ፋይሉ ትክክል አይደለም።" },
  factoryReset: { en: "Factory Reset", am: "ፋክተሪ ሪሴት" },
  dangerZone: { en: "Danger Zone", am: "አደገኛ ቀጠና" },
  wipeDesc: { en: "Select specific data sections to wipe, or perform a full system reset. Irreversible.", am: "የሚፈልጉትን የዳታ ክፍል ወይም ሙሉ ሲስተሙን ለማጥፋት ይምረጡ። ይህን መመለስ አይቻልም።" },
  configureDel: { en: "Configure Deletion", am: "ማጥፊያ አስተካክል" },
  selectDel: { en: "Select Data to Delete", am: "የሚጠፋውን ይምረጡ" },
  unselectAll: { en: "Unselect All", am: "ሁሉንም ተው" },
  selectAll: { en: "Select All", am: "ሁሉንም ምረጥ" },
  confirmDel: { en: "Confirm Deletion", am: "ማጥፋትን አረጋግጥ" },
  noSelection: { en: "No Selection", am: "የተመረጠ የለም" },
  noDataSelected: { en: "Please select at least one data type to delete.", am: "እባክዎ የሚጠፋ ቢያንስ አንድ ዓይነት ይምረጡ።" },
  confirmDeletion: { en: "Confirm Deletion", am: "ማጥፋትን አረጋግጥ" },
  deleteWarning: { en: "You are about to delete X data categories. Are you sure?", am: "X የዳታ ዓይነቶችን ሊያጠፉ ነው። እርግጠኛ ነዎት?" },
  finalWarning: { en: "FINAL WARNING", am: "የመጨረሻ ማስጠንቀቂያ" },
  irreversibleWarning: { en: "This action is IRREVERSIBLE. The selected data will be lost forever.", am: "ይህ እርምጃ አይመለስም። የተመረጠው መረጃ ለዘላለም ይጠፋል።" },
  backupSuccess: { en: "Backup generated successfully.", am: "ባካፕ በትክክል ተዘጋጅቷል።" },
  db_manpower: { en: "Manpower", am: "የሰው ኃይል" },
  db_incomeItems: { en: "Income Items", am: "የገቢ ዕቃዎች" },
  db_subsidies: { en: "Subsidies", am: "ድጎማዎች" },
  db_transfers: { en: "Transfers", am: "ዝውውሮች" },
  db_expenses: { en: "Expenses", am: "ወጪዎች" },
  db_refunds: { en: "Refunds", am: "ተመላሾች" },
  db_storeItems: { en: "Store Items", am: "የግምጃ ቤት ዕቃዎች" },
  db_storeOrders: { en: "Store Orders", am: "የትዕዛዝ መዝገብ" },
  db_foodProgramArchive: { en: "Food Prog. Archives", am: "የምግብ ፕሮግራም አርካይቭ" },
  db_notes: { en: "Notes", am: "ማስታወሻዎች" },

  // --- DATA EDITOR ---
  loadingDatabase: { en: "Loading Database...", am: "ዳታቤዝ በመጫን ላይ..." },
  cat_HR: { en: "HR", am: "የሰው ኃይል" },
  cat_Finance: { en: "Finance", am: "ፋይናንስ" },
  cat_Logistics: { en: "Logistics", am: "ሎጅስቲክስ" },
  cat_System: { en: "System", am: "ሲስተም" },
  recordUpdated: { en: "Record updated successfully.", am: "መዝገቡ በትክክል ተስተካክሏል።" },
  confirmDeleteTitle: { en: "Confirm Deletion", am: "ማጥፋትን አረጋግጥ" },
  confirmDeleteRecord: { en: "Are you sure you want to permanently delete this record? This action cannot be undone.", am: "ይህን መዝገብ ሙሉ በሙሉ ለማጥፋት እርግጠኛ ነዎት? ይህን መመለስ አይቻልም።" },
  recordDeleted: { en: "Record deleted successfully.", am: "መዝገቡ በትክክል ተሰርዟል።" },
  jsonError: { en: "JSON Error", am: "የ JSON ስህተት" },
  invalidJson: { en: "Invalid JSON format. Please fix syntax errors before saving.", am: "የ JSON አጻጻፍ ትክክል አይደለም። እባክዎ ከማስቀመጥዎ በፊት ስህተቱን ያስተካክሉ።" },
  collections: { en: "Collections", am: "ስብስቦች" },
  searchRecords: { en: "Search records...", am: "መዝገቦችን ይፈልጉ..." },
  noRecordsFound: { en: "No records found", am: "ምንም መዝገብ አልተገኘም" },
  changeQueryHint: { en: "Try changing the search query or select a different collection.", am: "የፍለጋ ቃሉን ይቀይሩ ወይም ሌላ ስብስብ ይምረጡ።" },
  editRecord: { en: "Edit Record", am: "መዝገብ አስተካክል" },
  dbEditCaution: { en: "Caution: Direct database editing. Ensure data integrity.", am: "ማስጠንቀቂያ፦ ቀጥታ የዳታቤዝ እርማት። የመረጃውን ትክክለኛነት ያረጋግጡ።" },
  complexData: { en: "Complex Data Object / Array", am: "ውስብስብ የዳታ ስብስብ (Array/Object)" },
  editJson: { en: "Edit JSON", am: "JSON አስተካክል" },
  applyJsonChanges: { en: "Apply JSON Changes", am: "የ JSON ለውጦችን ተግብር" },
  jsonEditor: { en: "JSON Editor", am: "JSON ማስተካከያ" },

  // --- OTHERS ---
  otherMeasurement: { en: "Other", am: "ሌላ መለኪያ" },

  // --- SEARCH PAGE ---
  marketTrends: { en: "Market Trends", am: "የገበያ ሁኔታ" },
  filters: { en: "Filters", am: "ማጣሪያዎች" },
  showDuplicatesOnly: { en: "Show Duplicates Only", am: "ተመሳሳይ መረጃዎችን ብቻ አሳይ" },
  aiIntelligenceReport: { en: "AI Intelligence Report", am: "የ AI ትንታኔ ሪፖርት" },
  processingNeuralAnalysis: { en: "Processing Neural Analysis...", am: "ትንታኔው እየተሰራ ነው..." },
  found: { en: "Found", am: "የተገኘው" },
  potentialDuplicates: { en: "Potential Duplicates", am: "ተመሳሳይ ሊሆኑ የሚችሉ" },
  page: { en: "Page", am: "ገጽ" },
  of: { en: "of", am: "ከ" },
  prev: { en: "Prev", am: "ቀዳሚ" },
  next: { en: "Next", am: "ቀጣይ" },
  noRecordsMatch: { en: "No records found in the database.", am: "በዳታቤዝ ውስጥ ምንም መረጃ አልተገኘም።" },
  adjustQueryHint: { en: "Try adjusting your query or disabling duplicate filters.", am: "እባክዎ ቃላቶቹን ይቀይሩ ወይም ማጣሪያውን ያጥፉ።" },
  trendAnalysisSelector: { en: "Trend Analysis Selector", am: "የትንታኔ መምረጫ" },
  chooseItemAnalyze: { en: "-- Choose Item to Analyze --", am: "-- ለመተንተን ዕቃ ይምረጡ --" },
  volatilityOverTime: { en: "Single Price Volatility Over Time", am: "የአንዱ ዋጋ መዋዠቅ በጊዜ ሂደት" },
  currentPrice: { en: "Current Price", am: "የአሁን ዋጋ" },
  firstRecorded: { en: "First Recorded", am: "መጀመሪያ የተመዘገበው" },
  lastRecorded: { en: "Last Recorded", am: "መጨረሻ የተመዘገበው" },
  noPriceHistory: { en: "No price history data found for this item.", am: "ለዚህ ዕቃ የዋጋ ታሪክ የለም።" },
  selectItemVisualize: { en: "Select an item from the dropdown to visualize market price changes.", am: "የገበያ ዋጋ ለውጥን ለማየት ከዝርዝሩ ዕቃ ይምረጡ።" },
  costFluctuationHint: { en: "See how costs fluctuate over days and months.", am: "ዋጋዎች በቀናት እና በወራት እንዴት እንደተቀያየሩ ይመልከቱ።" },
  searchPlaceholder: { en: "Search database records or ask AI...", am: "ከዳታቤዝ ይፈልጉ ወይም AI ይጠይቁ..." },
  
  // --- CHATBOT ---
  aiAssistant: { en: "AI Assistant", am: "AI ረዳት" },
  onlineReady: { en: "ONLINE • READY FOR ANALYSIS", am: "ኦንላይን • ለትንታኔ ዝግጁ" },
  typeQuestion: { en: "Type your question...", am: "ጥያቄዎን ይጻፉ..." },
  resetChat: { en: "Reset Chat", am: "ቻቱን አጥፋ" },
  howCanIHelp: { en: "How can I help you today?", am: "ዛሬ ምን ልርዳዎት?" },
  askAbout: { en: "Ask about expenses, trends, or predict future costs.", am: "ስለ ወጪ፣ የገበያ ሁኔታ ይጠይቁ ወይም የወደፊት ወጪዎችን ይተንብዩ።" },

  // --- NOTEBOOK PAGE ---
  fieldNotebook: { en: "Field Notebook", am: "የመስክ ማስታወሻ" },
  notebookSubtitle: { en: "Log incidents, plans, and general notes.", am: "ክስተቶችን፣ ዕቅዶችን እና ማስታወሻዎችን ይመዝግቡ።" },
  newEntry: { en: "New Entry", am: "አዲስ መዝገብ" },
  category: { en: "Category", am: "ምድብ" },
  subject: { en: "Subject", am: "ርዕስ" },
  enterTitle: { en: "Enter title...", am: "ርዕስ ያስገቡ..." },
  details: { en: "Details", am: "ዝርዝር" },
  writeDetails: { en: "Write details here...", am: "ዝርዝሩን እዚህ ይጻፉ..." },
  saveEntry: { en: "Save Entry", am: "መዝገቡን አስቀምጥ" },
  noNotes: { en: "No notes recorded yet.", am: "ምንም ማስታወሻ አልተመዘገበም።" },
  addFirstEntryHint: { en: "Use the form on the left to add your first entry.", am: "የመጀመሪያውን ለመመዝገብ በግራ በኩል ያለውን ቅጽ ይጠቀሙ።" },
  deleteNote: { en: "Delete Note", am: "ማስታወሻ አጥፋ" },
  deleteNoteConfirm: { en: "Are you sure you want to delete this note?", am: "ይህን ማስታወሻ ለማጥፋት እርግጠኛ ነዎት?" },
  generalNote: { en: "General Note", am: "ጠቅላላ ማስታወሻ" },
  incidentReport: { en: "Incident Report", am: "የክስተት ሪፖርት" },
  futurePlan: { en: "Future Plan", am: "የወደፊት ዕቅድ" },
  General: { en: "General Note", am: "ጠቅላላ ማስታወሻ" },
  Incident: { en: "Incident Report", am: "የክስተት ሪፖርት" },
  Plan: { en: "Future Plan", am: "የወደፊት ዕቅድ" },

  // --- QUERY TEMPLATES ---
  q_duplicates: { en: "Find potential duplicate entries in expenses", am: "በወጪዎች ላይ ተመሳሳይ ሊሆኑ የሚችሉትን ፈልግ" },
  q_expenses5000: { en: "Show all expenses over 5000 Birr", am: "ከ 5000 ብር በላይ ወጪዎችን አሳይ" },
  q_incomeVsExpense: { en: "Compare total income vs total expenses", am: "ጠቅላላ ገቢ እና ወጪን አወዳድር" },
  q_refunds: { en: "Summarize all refund reasons and amounts", am: "የተመላሽ ምክንያቶችን እና መጠኖችን አጠቃልል" },
  q_marketEfficiency: { en: "Analyze market purchase cost efficiency", am: "የገበያ ግዢ ዋጋ ቆጣቢነትን ተንትን" },
  q_topExpenditures: { en: "List top 5 highest expenditures", am: "ከፍተኛ 5 ወጪዎችን ዘርዝር" },
  
  // --- RESULT CATEGORIES ---
  subsidy: { en: "Subsidy", am: "ድጎማ" },
  transfer: { en: "Transfer", am: "ዝውውር" },

  // --- ABOUT PAGE ---
  name_andualem: { en: "Andualem Koriya", am: "አንዱዓለም ኮሪያ" },
  developer_bio: { en: "Developer Bio", am: "ስለ አዘጋጁ" },
  tech_portfolio: { en: "Technical Portfolio & Ambitions", am: "ቴክኒካል ልምድ እና ራዕይ" },
  past_projects: { en: "Past Projects", am: "የተሰሩ ፕሮጀክቶች" },
  adv_interests: { en: "Advanced Interests", am: "ልዩ ፍላጎቶች" },
  
  bio_p1: { 
    en: "I am a passionate Solution Architect and AI Engineer. Currently, I am a 2nd-year degree student in Cybersecurity, while actively advancing my skills in AI Engineering and Full Stack Development.", 
    am: "እኔ በሶሉሽን አርክቴክቸር እና AI ምህንድስና ላይ ከፍተኛ ፍላጎት ያለኝ ባለሙያ ነኝ። በአሁኑ ወቅት በሳይበር ደህንነት የ2ኛ ዓመት የዲግሪ ተማሪ ስሆን፣ ጎን ለጎን በAI እና ፉል ስታክ ዴቨሎፕመንት ክህሎቴን እያሳደግኩ እገኛለሁ።" 
  },
  bio_p2: { 
    en: "My journey began as a soldier where I was assigned duties as an Auditor, Store Man, and Buyer. While logistics wasn't my chosen profession, I adapted to the mission. I combined this hands-on field experience with my technical expertise to create ARMS (Auditing and Ration Management System).", 
    am: "ጉዞዬ የጀመረው እንደ ወታደር ሲሆን፣ በኦዲተርነት፣ በግምጃ ቤት ኃላፊነት እና በግዢ ሰራተኛነት ተመድቤ ሰርቻለሁ። ሎጅስቲክስ የመረጥኩት ሙያ ባይሆንም፣ ከተልዕኮው ጋር ራሴን አስተካክዬ ሰርቻለሁ። ይህን የመስክ ላይ ልምድ ከቴክኒካል እውቀቴ ጋር በማዋሃድ ARMS (የኦዲት እና ሬሽን አስተዳደር ሲስተም)ን መፍጠር ችያለሁ።" 
  },
  bio_p3: { 
    en: "My goal is to digitalize military systems—bridging the gap between manual operations and automation to improve efficiency, minimize human errors, and save critical operational time.", 
    am: "ዓላማዬ ወታደራዊ አሰራሮችን ወደ ዲጂታል መቀየር ሲሆን፣ በማኑዋል አሰራር እና በአውቶሜሽን መካከል ያለውን ክፍተት በመድፈን ቅልጥፍናን ለመጨመር፣ የሰው ስህተቶችን ለመቀነስ እና ወሳኝ የሆነውን የስራ ጊዜ ለመቆጠብ ነው።" 
  },

  proj_patient: { en: "Patient Registration System", am: "የታካሚዎች መመዝገቢያ ሲስተም" },
  proj_library: { en: "Library Management System", am: "የቤተ-መጻሕፍት አስተዳደር ሲስተም" },
  proj_ichat: { en: "i-Chat (Online Chatting System)", am: "i-Chat (የኦንላይን መልዕክት መለዋወጫ)" },
  proj_cloner: { en: "Python Web Cloner (File Structure Copier)", am: "Python Web Cloner (የፋይል መዋቅር ኮፒ ማድረጊያ)" },

  int_malware: { en: "Malware Development & Analysis", am: "ማልዌር ዴቨሎፕመንት እና ትንታኔ" },
  int_reverse: { en: "Reverse Engineering", am: "ሪቨርስ ኢንጂነሪንግ" },
  int_spyware: { en: "Spyware Tools & Ethical Hacking", am: "ስፓይዌር እና ኤቲካል ሀኪንግ" },
  int_automation: { en: "C++, Python & Bash Automation", am: "C++, Python እና Bash አውቶሜሽን" },

  // --- FIX: RECENT ACTIVITY TYPE BADGES (Home.tsx uses item.type.toLowerCase()) ---
  storeitem: { en: "Store Item", am: "የግምጃ ቤት ዕቃ" },
  storeorder: { en: "Store Order", am: "የግምጃ ቤት ትዕዛዝ" },
  note: { en: "Note", am: "ማስታወሻ" },
  notAvailable: { en: "N/A", am: "አይገኝም" },

  // --- LAYOUT: SYSTEM RESTORE DIALOG (was hardcoded English only) ---
  systemRestoreTitle: { en: "System Restore", am: "ሲስተም እንደገና ማስጀመር" },
  confirmRestoreSystemMsg: { en: "Are you sure you want to restore the system from backup?", am: "ከባካፕ ሲስተሙን መልሰው ማስጀመር ይፈልጋሉ?" },
  restoreFailedTitle: { en: "Restore Failed", am: "መመለስ አልተሳካም" },
  restoreFailedMsg: { en: "The file format is incorrect. It looks like a section export (Array), not a Full System Backup (Object). Use the specific page import tool instead.", am: "የፋይሉ አጻጻፍ ትክክል አይደለም። ይህ የአንድ ክፍል ውጤት (Array) እንጂ ሙሉ ሲስተም ባካፕ (Object) አይመስልም። እባክዎ የተለየውን የገጽ ማስመጫ መሳሪያ ይጠቀሙ።" },
  invalidBackupTitle: { en: "Invalid Backup", am: "ልክ ያልሆነ ባካፕ" },
  invalidBackupMsg: { en: "This file does not appear to be a valid ARMS database backup.", am: "ይህ ፋይል ትክክለኛ የARMS ዳታቤዝ ባካፕ አይመስልም።" },
  invalidFileTitle: { en: "Invalid File", am: "ልክ ያልሆነ ፋይል" },
  invalidFileMsg: { en: "The backup file structure is invalid.", am: "የባካፕ ፋይሉ አወቃቀር ልክ አይደለም።" },
  parsingErrorTitle: { en: "Parsing Error", am: "የንባብ ስህተት" },
  parsingErrorMsg: { en: "Failed to parse JSON file. It may be corrupted.", am: "JSON ፋይሉን ማንበብ አልተቻለም። ተበላሽቶ ሊሆን ይችላል።" },
  collapseSidebar: { en: "Collapse Sidebar", am: "የጎን ዝርዝርን ሰብስብ" },
  expandSidebar: { en: "Expand Sidebar", am: "የጎን ዝርዝርን ክፈት" },
  systemSecure: { en: "SYSTEM SECURE", am: "ሲስተሙ ደህንነቱ የተጠበቀ ነው" },

  // --- STORE: RATION HISTORY LOG ---
  rationHistoryTitle: { en: "Ration History (Monthly Log)", am: "የሬሽን ታሪክ (ወርሃዊ መዝገብ)" },
  noRationLogs: { en: "No ration logs found for this month.", am: "ለዚህ ወር ምንም የሬሽን መዝገብ የለም።" },

  // --- STORE: WEEKLY PROGRAM PAPER SETTINGS PLACEHOLDERS ---
  programTitlePlaceholder: { en: "Title", am: "ርዕስ" },
  programSubtitlePlaceholder: { en: "Subtitle", am: "ንዑስ ርዕስ" },
  footerLeftPlaceholder: { en: "Footer Left", am: "የግርጌ ግራ ጽሑፍ" },
  footerRightPlaceholder: { en: "Footer Right", am: "የግርጌ ቀኝ ጽሑፍ" },

  // --- STORE: EXAMPLE / HELPER PLACEHOLDERS ---
  egRiceOil: { en: "e.g. Rice, Oil", am: "ለምሳሌ፡ ሩዝ፣ ዘይት" },
  egMeat: { en: "e.g. Meat", am: "ለምሳሌ፡ ስጋ" },
  egUrgentHoliday: { en: "e.g. Urgent for holiday", am: "ለምሳሌ፡ ለበዓል አስቸኳይ" },
  noBuyer: { en: "No Buyer", am: "ገዢ የለም" },
  moreThan2Weeks: { en: "> 2 Weeks", am: "> 2 ሳምንት" },
  aiShortageFillerNote: { en: "AI Auto-Recommendation: Shortage Filler", am: "የ AI ራስ-ሰር ምክር፡ የጎደለውን መሙያ" },

  // --- INCOME: EXAMPLE / HELPER PLACEHOLDERS ---
  notesPlaceholder: { en: "Notes...", am: "ማስታወሻ..." },
  egRice: { en: "e.g. Rice", am: "ለምሳሌ፡ ሩዝ" },

  // --- ABOUT PAGE ---
  solutionArchitect: { en: "Solution Architect", am: "ሶሉሽን አርክቴክት" },
  aiEngineerRole: { en: "AI Engineer", am: "የ AI መሐንዲስ" },
  tagCyberSecurity: { en: "CYBER SECURITY", am: "የሳይበር ደህንነት" },
  tagAiMl: { en: "AI & ML", am: "AI እና ML" },
  tagFullStack: { en: "FULL STACK", am: "ፉል ስታክ" },
  emailLabel: { en: "Email", am: "ኢሜይል" },
  locationLabel: { en: "Location", am: "አድራሻ" },
  aboutLocationText: { en: "Ethiopian Air Force, Bishoftu", am: "የኢትዮጵያ አየር ኃይል, ቢሾፍቱ" },
  systemVersionStable: { en: "System Version 3.0.4 • Stable Build", am: "የሲስተም ስሪት 3.0.4 • የተረጋጋ ግንባታ" },

  // --- NOTEBOOK PAGE ---
  filteredTag: { en: "(Filtered)", am: "(ተጣርቷል)" },

  // --- LOGIN PAGE ---
  syncingCloudData: { en: "SYNCING CLOUD DATA...", am: "ክላውድ ዳታ በማመሳሰል ላይ..." },
  githubPersonalToken: { en: "GitHub Personal Token", am: "የ GitHub የግል ቶከን" },
  ownerOrganization: { en: "Owner / Organization", am: "ባለቤት / ድርጅት" },
  repositoryName: { en: "Repository Name", am: "የሪፖዚቶሪ ስም" },
  databaseFilePath: { en: "Database File Path", am: "የዳታቤዝ ፋይል መንገድ" },
  selectBadge: { en: "select", am: "ምረጥ" },

  // --- SEARCH PAGE ---
  unknownLabel: { en: "Unknown", am: "የማይታወቅ" },
  fromDateLabel: { en: "From", am: "ከ" },
  toDateLabel: { en: "to", am: "እስከ" },

  // --- AUDIT: RICH TEXT EDITOR TOOLBAR ---
  editorBold: { en: "Bold", am: "ደማቅ" },
  editorItalic: { en: "Italic", am: "ያዘነበለ" },
  editorUnderline: { en: "Underline", am: "ስር መስመር" },
  editorClearFormat: { en: "Clear Formatting", am: "ፎርማት አጽዳ" },
  editorDeleteSelection: { en: "Delete Selection", am: "የተመረጠውን ሰርዝ" },
  editorFontFamily: { en: "Font Family", am: "የፊደል ቅርፅ" },
  editorFontSize: { en: "Font Size", am: "የፊደል መጠን" },
  editorAlignLeft: { en: "Align Left", am: "ወደ ግራ አሰልፍ" },
  editorAlignCenter: { en: "Align Center", am: "መሃል ላይ አሰልፍ" },
  editorAlignRight: { en: "Align Right", am: "ወደ ቀኝ አሰልፍ" },
  editorNumberedList: { en: "Numbered List", am: "የቁጥር ዝርዝር" },
  editorBulletList: { en: "Bullet List", am: "የነጥብ ዝርዝር" },
  editorInsertTable: { en: "Insert Table", am: "ሰንጠረዥ አስገባ" },
  fontSansSerif: { en: "Sans-Serif", am: "Sans-Serif" },
  fontSerif: { en: "Serif", am: "Serif" },
  fontMonospace: { en: "Monospace", am: "Monospace" },
  sizeXSmall: { en: "X-Small", am: "እጅግ ትንሽ" },
  sizeSmall: { en: "Small", am: "ትንሽ" },
  sizeNormal: { en: "Normal", am: "መደበኛ" },
  sizeLarge: { en: "Large", am: "ትልቅ" },
  sizeXLarge: { en: "X-Large", am: "እጅግ ትልቅ" },
  sizeXXLarge: { en: "XX-Large", am: "በጣም ትልቅ" },
  sizeHuge: { en: "Huge", am: "ግዙፍ" },
  syncFromAutomatedTooltip: { en: "Sync / Reset to Automated Audit", am: "ከራስ-ሰር ኦዲት ጋር አመሳስል / ዳግም አስጀምር" },
  syncAutomatedBtn: { en: "Sync Automated", am: "ራስ-ሰር አመሳስል" },
  tableHeaderWord: { en: "Header", am: "ራስጌ" },
  tableCellWord: { en: "Cell", am: "ሕዋስ" },

  // --- AUDIT: CALCULATORS ---
  avgMarketCalcTitle: { en: "Average Market Calculator", am: "አማካይ የገበያ ካልኩሌተር" },
  standardCalcTitle: { en: "Standard Calc", am: "መደበኛ ካልኩሌተር" },

  // --- AUDIT: MANPOWER ROSTER ---
  activeLabel: { en: "Active", am: "አየተመገቡ ያሉ" },
  inactiveLabel: { en: "Inactive", am: "ያቋረጡ" },
  totalRoster: { en: "Total Roster", am: "ጠቅላላ የሰው ብዛት" },
  standardMonthlyRate: { en: "Standard Monthly Rate", am: "መደበኛ ወርሃዊ ተመን" },

  // --- AUDIT: DB ADMIN ---
  egUsername: { en: "e.g. username", am: "ለምሳሌ፡ የተጠቃሚ ስም" },
  egRepoName: { en: "e.g. repo-name", am: "ለምሳሌ፡ የሪፖ ስም" },
  egFolderFile: { en: "e.g. folder/file.json", am: "ለምሳሌ፡ folder/file.json" },
  verifyConnectTooltip: { en: "Verify credentials and connect to this path", am: "ማረጋገጫዎችን አረጋግጥ እና ከዚህ መንገድ ጋር ተገናኝ" },
  nowLabel: { en: "Now", am: "አሁን" },
  targetPathLabel: { en: "Target Path:", am: "የፋይል መንገድ፦" },
  databaseOwnerLabel: { en: "Database Owner:", am: "የዳታቤዝ ባለቤት፦" },
};

type LanguageContextType = {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<PropsWithChildren<{}>> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('arms_lang') as Language;
    if (saved) setLanguage(saved);
  }, []);

  const toggleLanguage = () => {
    const newLang = language === 'en' ? 'am' : 'en';
    setLanguage(newLang);
    localStorage.setItem('arms_lang', newLang);
  };

  const t = (key: string) => {
    if (!dictionary[key]) return key;
    return dictionary[key][language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
